### ISSUE TITLE
Build with a static CRT so that users don't need Visual Studio files

### ISSUE THREAD

**Issue by Lokathor** [iceiix/stevenarella#318]
Add the following to `.cargo/config` within the project:
```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i586-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
```
And then users will not need the visual studio redistributable files to run the program.

This *slightly* increases binary size (depending on how much of the Windows CRT you use), but it's a good trade.
